SA_Label/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('SA_Label_System.urls', namespace='SA_Label_System')),
    url(r'^admin/', admin.site.urls),
]

SA_Label_System/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signin$', views.signin, name='signin'),
    url(r'^signup$', views.signup, name='signup'),
    url(r'^signup_create_user$', views.signup_create_user, name='signup_create_user'),
    url(r'^label$', views.label, name='label'),
    url(r'^label_style_2$', views.label_style_2, name='label_style_2'),
    url(r'^user_logout$', views.user_logout, name='user_logout'),
    #url(r'^inform$', views.inform, name='inform'),
    url(r'^add_project', views.add_project, name='add_project'),
    url(r'^project_select$', views.project_select, name='project_select')
]

SA_Label_System/models.py
from django.db import models

# Create your models here.

class Label_Project(models.Model):
    project_name = models.CharField(max_length=200)
    project_time = models.DateTimeField()
    group_num = models.IntegerField(default=1)
    project_images_num = models.IntegerField(default=1)
    def __str__(self):
        return 'project_name: ' + self.project_name + '$'+'group_num: '+str(self.group_num)+'$'+'images_num: '+str(self.project_images_num)


class Project_Group(models.Model):
    project_name = models.ForeignKey(Label_Project, related_name='pg_project_name')
    group_name = models.CharField(max_length=200)  #the group name
    #group_num = models.ForeignKey(Label_Project, related_name='pg_group_num')
    group_images_num = models.IntegerField(default=1)  #how many images in this group
    group_labeled_num = models.IntegerField(default=0)

    def __str__(self):
        return 'project_name: '+self.project_name.project_name+'#'+'group_name: '+self.group_name+'#'+'group_images_num: '+str(self.group_images_num)+'#'+'group_labeled_num:'+str(self.group_labeled_num)


class Image_Basic_Info(models.Model):
    image_name = models.CharField(max_length=200)  # the length of image name is limited to 200 characters
    image_path = models.CharField(max_length=200)  # the length of image path is limited to 200 characters
    image_group = models.ForeignKey(Project_Group, related_name='ibi_image_group')  # the length of image group name is limited to 200 characters
    image_label_count = models.IntegerField(default=0)  # the times of the image that has been labeled
    image_type = models.IntegerField(default=1)
    image_project = models.ForeignKey(Label_Project, related_name='ibi_image_project')  # the label project name, the same as the dataset folder name

    def __str__(self):
        image_basic_info = 'image_project: ' + self.image_project.project_name +'\t'+ 'image_name:' + self.image_name + '\t' + 'image_type: ' + str(self.image_type) +'\t'+ 'image_path: ' + self.image_path + '#'+ 'image_group: ' + self.image_group.group_name + '#' + 'image_label_count: ' + str(self.image_label_count)
        return image_basic_info


class User_Basic_Info(models.Model):
    username = models.CharField(max_length=32)  #the length of username is limited to 32 characters
    password = models.CharField(max_length=32)  #the length of password is limited to 32 characters
    nickname = models.CharField(max_length=64)  #the length of nickname is limited to 64 characters
    email_address = models.CharField(max_length=128)  #the length of email address is limited 128 characters
    label_count = models.IntegerField(default=0)  # the times of user's labeling


    def __str__(self):
        user_basic_info = 'username: '+self.username + '#'+'nickname: '+self.nickname+'#'+'email_address: '+self.email_address+'||'+'label_count: '+str(self.label_count)
        #print(user_basic_info)
        return user_basic_info

class User_Setting(models.Model):
    user_basic_info = models.ForeignKey(User_Basic_Info, related_name='us_user_basic_info')
    style_select = models.IntegerField(default=1)
    project_select = models.CharField(default='.', max_length=200)

    def __str__(self):
        return 'user: '+self.user_basic_info.username+'#'+'style: '+str(self.style_select)+'#'+'project: '+self.project_select.project_name


class Image_Label_Info(models.Model):
    label_image_id = models.ForeignKey(Image_Basic_Info, related_name='label_image_id')  # use Image_Basic_Info primary key as foreign key
    base_image_id = models.ForeignKey(Image_Basic_Info, related_name='base_image_id')  # use Image_Basic_Info primary key as foreign key
    user_id = models.ForeignKey(User_Basic_Info)  # use User_Basic_Info primary key as foreign key
    image_score = models.FloatField(default=-1)  # the score that user give the two image
    label_time = models.DateTimeField()  # the time that user is labeling

    def __str__(self):
        return 'base_image_id: '+self.base_image_id.image_group.group_name+'||'+'label_image_id: '+self.label_image_id.image_name+'||'+'user_id: '+self.user_id.username


class Image_Label_Count(models.Model):
    user_id = models.ForeignKey(User_Basic_Info, related_name='count_user_id')
    image_id = models.ForeignKey(Image_Basic_Info, related_name='count_image_id')
    user_label_count = models.IntegerField(default=0)  # the number of times that this user has labeled the image

    def __str__(self):
        return 'user_id: '+self.user_id.username+'\t'+'image_id: '+self.image_id.image_name+'\t'+'user_label_count: '+str(self.user_label_count)

SA_Label_System/forms.py
from django import forms

class signup_form(forms.Form):
    input_email = forms.CharField(label='input_email', max_length=100)
    input_username = forms.CharField(label='input_username', max_length=100)
    input_password = forms.CharField(label='input_password', max_length=100)
    confirm_password = forms.CharField(label='confirm_password', max_length=100)

SA_Label_System/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from . import forms
from django.contrib.auth.models import User
from SA_Label_System.models import User_Basic_Info
from django.shortcuts import redirect, render_to_response
from django.contrib.auth import authenticate, login
from django.template.context_processors import csrf
from django.template import RequestContext
from .DataLoader import DataLoader
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from . import models
from django.utils import timezone
from django.contrib.auth import logout

# Create your views here.

def index(request):
    #data_loader = DataLoader()
    #data_loader.clean_files()
    #data_loader.load_dataset()
    return render(request, 'SA_Label_System/index.html')


def add_project(request):
    if not request.user.is_authenticated():
        return render(request, 'SA_Label_System/signin.html')
    if request.method == 'POST':
        project_name = request.POST['project-name']
        data_loader = DataLoader()
        data_loader.clean_project_files(project_name)
        data_loader.load_project_dataset(project_name)
        msg_id = 1
        return render(request, 'SA_Label_System/inform.html',{'msg_id':msg_id, 'project_name':project_name})
    return render(request, 'SA_Label_System/add_project.html')


def signin(request):
    if request.user.is_authenticated():
        username = request.user.username
        current_user_info = models.User_Basic_Info.objects.filter(username=username)[0]
        current_user_setting = models.User_Setting.objects.filter(user_basic_info=current_user_info)[0]
        # print('11111111111111111111111')
        #print(type(current_user_setting.project_select))
        if current_user_setting.project_select == '.':
            return redirect('/project_select')
        return redirect('/label')
    if request.method == 'POST':
        username = request.POST['input_username']
        password = request.POST['input_password']
        error_id = 0
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                #return render(request, 'SA_Label_System/label.html')
                current_user_info = models.User_Basic_Info.objects.filter(username=username)[0]
                current_user_setting = models.User_Setting.objects.filter(user_basic_info=current_user_info)[0]
                #print('11111111111111111111111')
                if current_user_setting.project_select == '.':
                    return redirect('/project_select')
                return redirect('/label')
            else:
                error_id = 2  # this account is blocked
                return render(request, 'SA_Label_System/error.html', {'error_id':error_id})
        else:
            error_id = 1  # the account does not exist
            return render(request, 'SA_Label_System/error.html', {'error_id':error_id})
    return render(request, 'SA_Label_System/signin.html')


def user_logout(request):
    logout(request)
    error_id = 4
    return render(request, 'SA_Label_System/error.html', {'error_id':error_id})


def signup(request):
    return render(request, 'SA_Label_System/signup.html')



def signup_create_user(request):
    if request.method == 'POST':
        form = forms.signup_form(request.POST)
        if request.POST['input_password'] != request.POST['confirm_password']:
            error_id = 3
            return render(request, 'SA_Label_System/error.html', {'error_id':error_id})
        if form.is_valid():
            user_info = models.User_Basic_Info.objects.filter(username=request.POST['input_username'])
            print(user_info)
            if user_info or form.cleaned_data['input_username']=='sph':
                error_id = 5
                return render(request, 'SA_Label_System/error.html', {'error_id':error_id})
            new_user = User.objects.create_user(username=form.cleaned_data['input_username'], email=form.cleaned_data['input_email'], password=form.cleaned_data['input_password'])
            new_user.save()
            new_user = User_Basic_Info(username=form.cleaned_data['input_username'], nickname='nickname', email_address=form.cleaned_data['input_email'], password=form.cleaned_data['input_password'], label_count=0)
            new_user.save()
            new_user_settings = models.User_Setting(user_basic_info=new_user)
            new_user_settings.save()
            return render(request, 'SA_Label_System/signin.html', {'username':form.cleaned_data['input_username']})
        else:
            print('form is invalid')
    return render(request, 'SA_Label_System/signup.html')


def project_select(request):
    if not models.Label_Project.objects.all().exists():
        msg_id = 2
        return render(request, 'SA_Label_System/inform.html', {'msg_id':msg_id})
    #print('enter label')
    if not request.user.is_authenticated():
        return render(request, 'SA_Label_System/signin.html')
    #print('111111111111111111')
    if request.method == 'POST':
        project_name = request.POST['project_select']
        #print(project_name)
        current_username = request.user.username
        current_user_info = models.User_Basic_Info.objects.get(username=current_username)  # get the current username
        current_user_settings = models.User_Setting.objects.filter(user_basic_info=current_user_info)[0]  # get current user settings
        #label_project_info = models.Label_Project.objects.filter(project_name=project_name)[0]
        current_user_settings.project_select = project_name
        current_user_settings.save()
        #print('222222222222222222222')
        return redirect('/label')
    #print('33333333333333333333')
    projects = models.Label_Project.objects.all()
    return render(request, 'SA_Label_System/carousel.html', {'projects':projects})



def label_style_2(request):
    if not models.Label_Project.objects.all().exists():
        msg_id = 2
        return render(request, 'SA_Label_System/inform.html', {'msg_id':msg_id})

    if not request.user.is_authenticated():
        return render(request, 'SA_Label_System/signin.html')
    if request.method == 'POST':
        #print('label post')
        current_username = request.user.username  #get the current username
        #print(current_username)
        base_image_path = request.POST['absolute_base_image_path']
        label_image_path = request.POST['absolute_label_image_path']
        #print(base_image_path)
        #print(label_image_path)
        current_user_info = models.User_Basic_Info.objects.get(username=current_username)  #get the current username
        #print(current_user_info)
        current_user_info.label_count += 1
        current_user_info.save()
        label_image_info = models.Image_Basic_Info.objects.get(image_path=label_image_path)
        base_image_info = models.Image_Basic_Info.objects.get(image_path=base_image_path)
        #print(current_user_info)
        #print(label_image_info)
        #print(base_image_info)
        label_image_info.image_label_count += 1
        label_image_info.save()
        #print(label_image_info.image_label_count)
        #print(current_user_info.id)
        #print(label_image_info.id)
        #print(models.Image_Label_Count.objects.all())
        #image_label_count_info = models.Image_Label_Count.objects.all()
        #print(image_label_count_info)
        image_label_count_info = models.Image_Label_Count.objects.filter(user_id=current_user_info.id, image_id=label_image_info.id)
        #print('1111111111111')
        if not image_label_count_info:  #if not exists
            #print('22222222222222')
            image_label_count_info = models.Image_Label_Count(user_id=current_user_info, image_id=label_image_info, user_label_count=1)
            image_label_count_info.save()
            #print('3333333333333333333')
        else:
            image_label_count_info = image_label_count_info[0]
            #print(image_label_count_info)
            image_label_count_info.user_label_count += 1
            image_label_count_info.save()

        image_label_info = models.Image_Label_Info(label_image_id=label_image_info, base_image_id=base_image_info, user_id=current_user_info, image_score=float(request.POST['score']), label_time=timezone.now())
        image_label_info.save()

        return redirect('/label_style_2')
    current_username = request.user.username
    current_user_info = models.User_Basic_Info.objects.filter(username=current_username)[0]
    current_user_settings = models.User_Setting.objects.filter(user_basic_info=current_user_info)[0]
    current_project = current_user_settings.project_select
    data_loader = DataLoader()
    data_loader.generate_project_images_path(current_project)
    base_image_path = data_loader.get_base_image_path()
    label_image_path = data_loader.get_label_image_path()
    absolute_base_image_path = data_loader.get_absolute_base_image_path()
    absolute_label_image_path = data_loader.get_absolute_label_image_path()
    return render(request, 'SA_Label_System/label_style_2.html', {'base_image_path':base_image_path, 'label_image_path':label_image_path, 'absolute_base_image_path':absolute_base_image_path, 'absolute_label_image_path':absolute_label_image_path})




def label(request):
    #print('enter label')
    if not models.Label_Project.objects.all().exists():
        msg_id = 2
        return render(request, 'SA_Label_System/inform.html', {'msg_id':msg_id})
    if not request.user.is_authenticated():
        return render(request, 'SA_Label_System/signin.html')
    if request.method == 'POST':
        #print('label post')
        current_username = request.user.username  #get the current username
        #print(current_username)
        base_image_path = request.POST['absolute_base_image_path']

SA_Label_System/templates/SA_Label_System/label.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>Label Page</title>

    <!-- Bootstrap core CSS -->
    <link href="../../static/SA_Label_System/css/bootstrap/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../static/SA_Label_System/css/assets/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../../static/SA_Label_System/css/label.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../static/SA_Label_System/js/assets/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <style>
      body {
          background-color: #999;
      }

      .img-div {
          float: left;
          margin: 10px;
      }

      .img-label-button-div {
          margin-top: 10px;
      }

      .clear-float {
          clear: both;
      }
  </style>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'SA_Label_System:index' %}">SA Label System</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'SA_Label_System:index' %}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
            <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'SA_Label_System:label_style_2' %}">Switch Style</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="{% url 'SA_Label_System:user_logout' %}">Logout</a></li>
                  </ul>
                </li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="starter-template">
        <h1>Label Page</h1>
        <p class="lead"></p>
        <!--<img src="../../static/SA_Label_System/img/1-13316.png" class="img-rounded">
        <img src="../../static/SA_Label_System/img/2-13656.png" class="img-rounded">-->
        <div class="container">
        <div class="img-div"><img src="{{ base_image_path }}" class="img-rounded"></div>
        <div class="img-div">
            <div class="img-label-div"><img src="{{ label_image_path }}" class="img-rounded" id="label_image"></div>
            <div class="img-label-button-div"><button type="button" class="btn btn-lg btn-primary" onclick="rotate_label_image()">Rotate</button></div>
        </div>
        </div>
        <div class="clear-float"></div>
      </div>
         <form action="{% url 'SA_Label_System:label' %}" method="post">{% csrf_token %}
      <!--<div class="row" >-->
            <div class="input-group">
              <input type="number" class="form-control" min="0" max="5" placeholder="Score" name="score" required autofocus>
              <input type="hidden" value="{{ absolute_base_image_path }}" name="absolute_base_image_path">
              <input type="hidden" value="{{ absolute_label_image_path }}" name="absolute_label_image_path">
                <input type="hidden" value="1" name="label_style">
              <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Submit</button>
              </span>
            </div><!-- /input-group -->
         </form>
        <!--</div><!-- /.row -->
        <p class="lead">说明:</p>
        <p>左图为基准图片, 右图为需要标注的图片, 点击Rotate按钮可以旋转标注图片</p>
        <p>标注分数为0,1,2,3,4,5, 不同分数表示的含义如下:</p>
        <p>5. 左图和右图是相同图&nbsp&nbsp&nbsp</p>
        <p>4. 左图和右图非常相似&nbsp&nbsp&nbsp</p>
        <p>3. 左图和右图比较相似&nbsp&nbsp&nbsp</p>
        <p>2. 左图和右图有点相似&nbsp&nbsp&nbsp</p>
        <p>1. 左图和右图完全不相似</p>
        <p>0. 无法确定两图相似关系</p>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../../static/SA_Label_System/js/label.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../static/SA_Label_System/js/bootstrap/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../static/SA_Label_System/js/assets/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

SA_Label_System/templates/SA_Label_System/label_style_2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="">

    <title>Label Page</title>

    <!-- Bootstrap core CSS -->
    <link href="../../static/SA_Label_System/css/bootstrap/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../static/SA_Label_System/css/assets/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../../static/SA_Label_System/css/label.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../static/SA_Label_System/js/assets/ie-emulation-modes-warning.js"></script>
    <script src="../../static/SA_Label_System/js/label_style_2.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <style>
      body {
          background-color: #999;
      }

      .img-div {
          float: left;
          margin: 10px;
      }

      .img-label-button-div {
          margin-top: 10px;
      }

      .clear-float {
          clear: both;
      }

      #div-radio-group {
          color: black;
          font-size: 20px;
      }

      .input-group {
          max-width: 400px;
          padding: 15px;
          margin: 0 auto;
          background-color: #c9e2b3;
}
  </style>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'SA_Label_System:index' %}">SA Label System</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'SA_Label_System:index' %}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
            <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'SA_Label_System:label' %}">Switch Style</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="{% url 'SA_Label_System:user_logout' %}">Logout</a></li>
                  </ul>
                </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">

      <div class="starter-template">
        <h1>Label Page</h1>
        <p class="lead"></p>
        <!--<img src="../../static/SA_Label_System/img/1-13316.png" class="img-rounded">
        <img src="../../static/SA_Label_System/img/2-13656.png" class="img-rounded">-->
        <div class="container">
        <div class="img-div"><img src="{{ base_image_path }}" class="img-rounded"></div>
        <div class="img-div">
            <div class="img-label-div"><img src="{{ label_image_path }}" class="img-rounded" id="label_image"></div>
            <div class="img-label-button-div"><button type="button" class="btn btn-primary" onclick="rotate_label_image()">Rotate</button></div>
        </div>
        </div>
        <div class="clear-float"></div>
      </div>
        <form action="{% url 'SA_Label_System:label_style_2' %}" method="post">{% csrf_token %}
              <div class="form-group input-group" id="div-radio-group">
                <label class="radio-inline">
                  <input type="radio"  value="0" name="score" checked="checked">0
                </label>
                <label class="radio-inline">
                  <input type="radio"  value="1" name="score">1
                </label>
                <label class="radio-inline">
                  <input type="radio"  value="2" name="score">2
                </label>
                <label class="radio-inline">
                  <input type="radio"  value="3" name="score">3
                </label>
                <label class="radio-inline">
                  <input type="radio"  value="4" name="score">4
                </label>
                <label class="radio-inline">
                  <input type="radio"  value="5" name="score">5
                </label>
                <span class="input-group-btn">
                <button class="btn btn-primary" type="submit">Submit</button>
              </span>
              </div>
            <input type="hidden" value="{{ absolute_base_image_path }}" name="absolute_base_image_path">
            <input type="hidden" value="{{ absolute_label_image_path }}" name="absolute_label_image_path">
            <input type="hidden" value="2" name="label_style">
        </form>
                <p class="lead">说明:</p>
        <p>左图为基准图片, 右图为需要标注的图片, 点击Rotate按钮可以旋转标注图片</p>
        <p>标注分数为0,1,2,3,4,5, 不同分数表示的含义如下:</p>
        <p>5. 左图和右图是相同图&nbsp&nbsp&nbsp</p>
        <p>4. 左图和右图非常相似&nbsp&nbsp&nbsp</p>
        <p>3. 左图和右图比较相似&nbsp&nbsp&nbsp</p>
        <p>2. 左图和右图有点相似&nbsp&nbsp&nbsp</p>
        <p>1. 左图和右图完全不相似</p>
        <p>0. 无法确定两图相似关系</p>
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../../static/SA_Label_System/js/label.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../static/SA_Label_System/js/bootstrap/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../static/SA_Label_System/js/assets/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>